version: 0.{build}

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2017
platform: x86
configuration: Release
clone_depth: 1

cache:
- C:\mod-manifest-gen.exe

init:
- ps: mkdir C:\SoundOverhaul
- ps: Set-Content -Value "Name=Sound Overhaul 3`r`nDescription=Improves volume handling, restores missing sounds and fixes sound bugs. Replaces sound effects with high quality Dreamcast rips.`r`nAuthor=PkR & TheLegendOfXela`r`nVersion=$env:APPVEYOR_BUILD_VERSION`r`nDLLFile=sadx-sound-overhaul.dll`r`nUpdateUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SoundOverhaul/`r`nChangelogUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Changelog.txt" -Path C:\SoundOverhaul\mod.ini
- cmd: choco install wget --version 1.20
- cmd: cd \
- cmd: wget -np --no-parent -nH --cut-dirs 4 -nc "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/mod-manifest-gen.exe"
- cmd: wget -r -np --no-parent -nH --cut-dirs 4 -nc --reject htm,html,tmp,dll "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SoundOverhaul/"
- cmd: cd C:\projects\sadx-sound-overhaul

before_build:
- cmd: git submodule update --init --recursive

build:
  project: sadx-sound-overhaul.sln
  
after_build:
- cmd: copy C:\projects\sadx-sound-overhaul\bin\sadx-sound-overhaul.dll C:\SoundOverhaul\sadx-sound-overhaul.dll
- ps: $MyProcess = Start-Process "C:\mod-manifest-gen.exe" -Wait -PassThru -ArgumentList "C:\SoundOverhaul"
- cmd: cd C:\
- cmd: 7z a SoundOverhaul.7z SoundOverhaul
- cmd: move SoundOverhaul.7z C:\projects\sadx-sound-overhaul\bin\SoundOverhaul.7z

artifacts:
- path: bin\SoundOverhaul.7z
